# Generated by Django 3.2.9 on 2022-07-10 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('queue', models.CharField(choices=[(0, 'Очередь 1'), (1, 'Очередь 2'), (2, 'Очередь 3'), (3, 'Очередь 4')], default='-', max_length=20, verbose_name='Очередь')),
                ('rule_range', models.IntegerField(default='-', verbose_name='Ранг')),
                ('creator', models.CharField(max_length=20, verbose_name='Пользователь, который создал правило')),
                ('updator', models.CharField(max_length=20, verbose_name='Пользователь, который последним изменил правило')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Дата создания правила')),
                ('update_date', models.DateField(auto_now=True, verbose_name='Дата последнего изменения правила')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('AND', 'AND'), ('OR', 'OR')], default='-', max_length=5, verbose_name='Тип')),
                ('attribute', models.CharField(choices=[(0, 'Тип задания 1'), (1, 'Тип задания 2'), (2, 'Тип задания 3'), (3, 'Тип клиента'), (4, 'Признак запроса ОГВ'), (5, 'Признак соответствия суммы критериям НС'), (6, 'Статус'), (7, 'Предпочитаемый способ связи'), (8, 'Тип действия'), (9, 'Результат действия')], default='-', max_length=20, verbose_name='Атрибут')),
                ('operator', models.CharField(choices=[(0, '='), (1, '!='), (2, 'in'), (3, 'not in'), (4, 'like'), (5, 'not like')], default='-', max_length=20, verbose_name='Оператор')),
                ('value', models.CharField(max_length=200, verbose_name='Оператор')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.rule', verbose_name='Правило')),
            ],
        ),
    ]
