# Generated by Django 3.2.9 on 2022-07-10 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='queue',
            field=models.IntegerField(choices=[(0, 'Очередь 1'), (1, 'Очередь 2'), (2, 'Очередь 3'), (3, 'Очередь 4')], default='-', verbose_name='Очередь'),
        ),
        migrations.AlterField(
            model_name='task',
            name='attribute',
            field=models.IntegerField(choices=[(0, 'Тип задания 1'), (1, 'Тип задания 2'), (2, 'Тип задания 3'), (3, 'Тип клиента'), (4, 'Признак запроса ОГВ'), (5, 'Признак соответствия суммы критериям НС'), (6, 'Статус'), (7, 'Предпочитаемый способ связи'), (8, 'Тип действия'), (9, 'Результат действия')], default='-', verbose_name='Атрибут'),
        ),
        migrations.AlterField(
            model_name='task',
            name='operator',
            field=models.IntegerField(choices=[(0, '='), (1, '!='), (2, 'in'), (3, 'not in'), (4, 'like'), (5, 'not like')], default='-', verbose_name='Оператор'),
        ),
        migrations.AlterField(
            model_name='task',
            name='value',
            field=models.CharField(max_length=200, verbose_name='Значение'),
        ),
    ]
