# Generated by Django 3.2.9 on 2022-07-10 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20220710_1753'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Правило маршрутизации заданий', 'verbose_name_plural': 'Правила маршрутизации заданий'},
        ),
        migrations.AlterField(
            model_name='rule',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания правила'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения правила'),
        ),
    ]
