# Generated by Django 3.2.9 on 2022-07-12 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20220710_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionaries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Value_for_type123',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='rule',
            name='rule_range',
            field=models.IntegerField(unique=True, verbose_name='Ранг'),
        ),
        migrations.AlterField(
            model_name='task',
            name='operator',
            field=models.CharField(choices=[('=', '='), ('!=', '!='), ('in', 'in'), ('not in', 'not in'), ('like', 'like'), ('not like', 'not like')], default='-', max_length=200, verbose_name='Оператор'),
        ),
    ]
